---
permalink: protect-scc/concept_snapcenter_custom_plug_ins_overview.html 
sidebar: sidebar 
keywords: SnapCenter Custom Plug-ins 
summary: Você pode desenvolver plug-ins personalizados para aplicações que usa e usar o SnapCenter para fazer backup, restauração ou clone dessas aplicações. Como outros plug-ins do SnapCenter, seus plug-ins personalizados atuam como componentes do lado do host do software, permitindo a proteção de dados com reconhecimento de aplicativos e o gerenciamento de recursos. 
---
= Visão geral dos plug-ins personalizados do SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desenvolver plug-ins personalizados para aplicações que usa e usar o SnapCenter para fazer backup, restauração ou clone dessas aplicações. Como outros plug-ins do SnapCenter, seus plug-ins personalizados atuam como componentes do lado do host do software NetApp SnapCenter, permitindo a proteção de dados com reconhecimento de aplicações e o gerenciamento de recursos.

Quando os plug-ins personalizados são instalados, você pode usar a tecnologia SnapCenter com NetApp SnapMirror para criar cópias espelhadas de conjuntos de backup em outro volume e usar a tecnologia NetApp SnapVault para executar a replicação de backup disco para disco. Os plug-ins personalizados podem ser usados em ambientes Windows e Linux.


NOTE: SnapCenterCLI não suporta comandos de plug-ins personalizados do SnapCenter.

O NetApp fornece plug-ins personalizados MySQL e DB2 com o software SnapCenter 2,0 e posterior e plug-in personalizado MongoDB de 3,0 e posterior. Esses plug-ins podem ser baixados do https://automationstore.netapp.com/home.shtml["Repositório de automação do storage da NetApp"^].


NOTE: Os plug-ins personalizados MySQL, DB2 e MongoDB são compatíveis apenas com as comunidades NetApp.

Pode criar os seus próprios plug-ins personalizados consultando link:concept_develop_a_plug_in_for_your_application.html["Desenvolva um plug-in para sua aplicação"^]o .
